#!/bin/sh

# $Id$

# This file is part of Duro, a relational database library.
# Copyright (C) 2003 René Hartmann
# 
# Duro is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# Duro is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Duro; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../lib

failure () {
    echo Test failed.
    exit
}

# Invoke a test application and compare output
calltest () {
    echo $1
    if ./$1 > /tmp/duro$$; then true ; else echo $?; failure; fi
    if diff /tmp/duro$$ $1_output; then : ; else failure; fi
}

calltest tupletest

rm -rf db
mkdir db

if ./prepare; then :; else failure; fi

echo lstables
if ../util/lstables db TEST | sort > /tmp/duro$$; then true ; else echo $?; failure; fi
if diff /tmp/duro$$ lstables_output; then : ; else failure; fi

calltest test_select
calltest test_minus
calltest test_union
calltest test_intersect
calltest test_extend
calltest test_join
calltest test_keys
calltest test_project
calltest test_aggregate
calltest test_update
calltest test_delete
calltest test_null

rm /tmp/duro$$

echo Dropping tables
if ../util/droptable db TEST EMPS1 EMPS2 DEPTS DEEDUM; then :; else
    failure
fi

echo Dropping DB
if ../util/dropdb db TEST; then :; else
    failure
fi

echo Test completed successfully.
