all:
	scons
all_pg:
	scons postgresql=true
test:
	scons test
test_pg:
	scons test postgresql=true
testbins:
	scons testbins
apidocs:
	scons apidocs
jni:
	scons jni
javadocs:
	scons javadocs
dist:
	scons dist
clean:
	scons -c .
