/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_duro_DInstance */

#ifndef _Included_net_sf_duro_DInstance
#define _Included_net_sf_duro_DInstance
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sf_duro_DInstance
 * Method:    initInterp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_duro_DInstance_initInterp
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_duro_DInstance
 * Method:    destroyInterp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_duro_DInstance_destroyInterp
  (JNIEnv *, jobject);

/*
 * Class:     net_sf_duro_DInstance
 * Method:    execute
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_sf_duro_DInstance_execute
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_sf_duro_DInstance
 * Method:    evaluate
 * Signature: (Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_net_sf_duro_DInstance_evaluate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_sf_duro_DInstance
 * Method:    setVariable
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_net_sf_duro_DInstance_setVariable
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
